### ISSUE TITLE
[19530c7c] Error in plotBaMMLogo.R code

### ISSUE THREAD

**Issue by WanwanGe** [soedinglab/BaMM_webserver#112]
> bammmotif.utils.misc.CommandFailureException: 'plotBaMMLogo.R' '/code/media/19530c7c-9d7b-4040-a24c-29e743d51b24/Output/' 'PausingSequences.Rep1' '0' '--web' '1'

**Comment by WanwanGe** [comment]
In this case, the `ihbp` and `hbp` files are not generated for plotting the logos, in the motif-motif comparison.

**Comment by croth1** [comment]
This error is again due to the additional dot in the filename. This time the conditional->joint probability script was affected. Fixed in the latest dev version.
