### ISSUE TITLE
visualize motif occurences in bammscan

### ISSUE THREAD

**Issue by croth1** [soedinglab/BaMM_webserver#42]
currently the webserver has no functionality to visualize motif hits on sequences. This would be a very nice feature that we can queue for some time after the submission.

**Comment by WanwanGe** [comment]
I only found the IGV app for visualizing .bed file. It is a java application which can only be downloaded locally. So maybe we only provide .bed file in the output package?

**Comment by croth1** [comment]
Another option is to convert the bed to bigBed format and visualize it with an online genome browser (e.g. UCSC)
