### ISSUE TITLE
[1a38acd0] segfault in BaMM fdr

### ISSUE THREAD

**Issue by croth1** [soedinglab/BaMM_webserver#96]
😖

**Comment by WanwanGe** [comment]
Fixed it. The problem was caused by subsampling the positive sequences. It is now fixed on BaMMmotif2/master branch.

**Comment by croth1** [comment]
apparently also affected: ec1f3b85

**Comment by WanwanGe** [comment]
Yes, confirmed that!

**Comment by croth1** [comment]
should be fixed now on both main and dev server.
